// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerated so docs created/edited in the /admin CMS appear automatically.
  // Order is controlled by each doc's `sidebar_position` front-matter.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
